name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Permet de déclencher manuellement depuis GitHub

jobs:

  # ==========================================
  # 1. Tests automatiques
  # ==========================================
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: pip install -r requirements-dev.txt

      - name: Lancer les tests
        run: pytest -v


  # ==========================================
  # 2. Build + publication de l'image Docker
  # ==========================================
  build-image:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t pos-reporting:${{ github.sha }} .

      - name: Se connecter à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculer le nom de l'image
        run: |
          echo "IMAGE=ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Taguer et publier l'image
        run: |
          docker tag pos-reporting:${{ github.sha }} ${{ env.IMAGE }}:latest
          docker tag pos-reporting:${{ github.sha }} ${{ env.IMAGE }}:${{ github.sha }}

          docker push ${{ env.IMAGE }}:latest
          docker push ${{ env.IMAGE }}:${{ github.sha }}


  # ==========================================
  # 3. Déploiement automatique sur Kubernetes
  # ==========================================
  deploy:
    needs: build-image
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:

      - name: Vérifier le cluster Kubernetes
        run: |
          kubectl get nodes

      - name: Déployer la nouvelle image
        run: |
          kubectl -n pos-reporting set image deployment/pos-reporting \
            pos-reporting=ghcr.io/souha-mejri/pos_reporting:latest

      - name: Attendre le déploiement
        run: |
          kubectl -n pos-reporting rollout status deployment/pos-reporting --timeout=180s

      - name: Vérifier le pod
        run: |
          kubectl -n pos-reporting get pods -o wide